<?php

namespace DoctrineProxies\__CG__\App\Models;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AttributeItem extends \App\Models\AttributeItem implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'attribute' => [parent::class, 'attribute', null, 8],
        "\0".'*'."\0".'displayValue' => [parent::class, 'displayValue', null, 8],
        "\0".'*'."\0".'id' => [parent::class, 'id', null, 8],
        "\0".'*'."\0".'productItems' => [parent::class, 'productItems', null, 8],
        "\0".'*'."\0".'value' => [parent::class, 'value', null, 8],
        'attribute' => [parent::class, 'attribute', null, 8],
        'displayValue' => [parent::class, 'displayValue', null, 8],
        'id' => [parent::class, 'id', null, 8],
        'productItems' => [parent::class, 'productItems', null, 8],
        'value' => [parent::class, 'value', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
